name: golden_scenario_env
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets==8.1.0
  - matplotlib==3.7.2
  - notebook==7.0.3
  - numpy==1.23.5
  - pandas==2.0.3
  - pydotplus==2.0.2
  - scikit-learn==1.3.0
  - tensorflow==2.12.1
  - ydata-profiling==4.5.1
  # pin typeguard to 2.13.3 to avoid a runtime issue with ydata-profiling
  - typeguard==2.13.3
  # auto register conda environments as ipython kernels in jupyter
  - nb_conda_kernels==2.3.1
